---
- name: Configure webserver with nginx
  hosts: webservers
  become: true
  become_method: sudo

  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Copy nginx config file
      ansible.builtin.copy:
        src: "nginx.conf"
        dest: /etc/nginx/sites-available/default
        owner: admin
        group: admin
        mode: "0644"

    - name: Enable nginx configuration
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: true

    - name: Copy index.html
      ansible.builtin.template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        owner: admin
        group: admin
        mode: "0644"

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
